name: pacoguerra
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#110046'
    - '#3500a9'
    - '#252965'
    - '#0d1a41'
  brandStrength: 0.6670716484077275
  lightness: 0.4396822222042829
  saturation: 0.49531420273706317
  rhythmicContrast: 0.7448516839649528
purpose: []
